// Copyright Red Hat

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AuthRealmListerExpansion allows custom methods to be added to
// AuthRealmLister.
type AuthRealmListerExpansion interface{}

// AuthRealmNamespaceListerExpansion allows custom methods to be added to
// AuthRealmNamespaceLister.
type AuthRealmNamespaceListerExpansion interface{}

// StrategyListerExpansion allows custom methods to be added to
// StrategyLister.
type StrategyListerExpansion interface{}

// StrategyNamespaceListerExpansion allows custom methods to be added to
// StrategyNamespaceLister.
type StrategyNamespaceListerExpansion interface{}
