// Copyright Red Hat

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AuthRealmListerExpansion allows custom methods to be added to
// AuthRealmLister.
type AuthRealmListerExpansion interface{}

// AuthRealmNamespaceListerExpansion allows custom methods to be added to
// AuthRealmNamespaceLister.
type AuthRealmNamespaceListerExpansion interface{}

// ClusterOAuthListerExpansion allows custom methods to be added to
// ClusterOAuthLister.
type ClusterOAuthListerExpansion interface{}

// ClusterOAuthNamespaceListerExpansion allows custom methods to be added to
// ClusterOAuthNamespaceLister.
type ClusterOAuthNamespaceListerExpansion interface{}

// IDPConfigListerExpansion allows custom methods to be added to
// IDPConfigLister.
type IDPConfigListerExpansion interface{}

// IDPConfigNamespaceListerExpansion allows custom methods to be added to
// IDPConfigNamespaceLister.
type IDPConfigNamespaceListerExpansion interface{}

// StrategyListerExpansion allows custom methods to be added to
// StrategyLister.
type StrategyListerExpansion interface{}

// StrategyNamespaceListerExpansion allows custom methods to be added to
// StrategyNamespaceLister.
type StrategyNamespaceListerExpansion interface{}
